apiVersion: v1
kind: Service
metadata:
  name: traveltrack-api
  namespace: traveltrack
spec:
  selector:
    app: traveltrack-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
