---
# Source: traveltrack-api/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "tt-traveltrack-api-config"
  labels:
    
    app.kubernetes.io/name: traveltrack-api
    helm.sh/chart: traveltrack-api-0.1.0
    app.kubernetes.io/instance: tt
    app.kubernetes.io/managed-by: Helm
data:
  APP_VERSION: "0.1.0"
  PORT: "8080"
---
# Source: traveltrack-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tt-traveltrack-api
  labels:
    
    app.kubernetes.io/name: traveltrack-api
    helm.sh/chart: traveltrack-api-0.1.0
    app.kubernetes.io/instance: tt
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    
    app.kubernetes.io/name: traveltrack-api
    app.kubernetes.io/instance: tt
  ports:
    - name: http
      port: 8080
      targetPort: http
---
# Source: traveltrack-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-traveltrack-api
  labels:
    
    app.kubernetes.io/name: traveltrack-api
    helm.sh/chart: traveltrack-api-0.1.0
    app.kubernetes.io/instance: tt
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      
      app.kubernetes.io/name: traveltrack-api
      app.kubernetes.io/instance: tt
  template:
    metadata:
      labels:
        
        app.kubernetes.io/name: traveltrack-api
        app.kubernetes.io/instance: tt
      annotations:
        
        {}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: traveltrack-api
          image: "traveltrack-api:0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: tt-traveltrack-api-config
                  key: APP_VERSION
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: tt-traveltrack-api-config
                  key: PORT
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      nodeSelector:
        
        {}
      tolerations:
        
        []
      affinity:
        
        {}
