apiVersion: v1
kind: Service
metadata:
  name: traveltrack-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: traveltrack-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
