apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cafeteria

resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cafeteria

images:
  - name: cafeteria-app
    newName: cafeteria-app
    newTag: latest