apiVersion: v2
name: traveltrack-api
description: TravelTrack API (Node.js + TS) - Helm chart
version: 0.1.0           # versión del chart
appVersion: "0.1.0"       # versión de la app (informativa)
type: application
