apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - servicemonitor.yaml
  - prometheusrule.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cafeteria