image:
  repository: "ghcr.io/cardo88/traveltrack-api"
  tag: "2025.11.09.00.00"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

config:
  appVersion: "0.1.0"
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
