apiVersion: v2
name: snake-app
description: Helm chart para desplegar el frontend Snake en Kubernetes
type: application
version: 0.1.0        # versión del chart
appVersion: "1.0.0"   # versión de la app
