replicaCount: 1

image:
  repository: snake-app
  tag: "v1-blue"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30095

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false