apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab4-demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lab4-demo.name" . }}
    helm.sh/chart: {{ include "lab4-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lab4-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lab4-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "lab4-demo.fullname" . }}-config
          resources:
{{- toYaml .Values.resources | nindent 12 }}
